package aste;

import java.io.Serializable;

public class Richiesta implements Serializable {
	public TipoRichiesta tipoRichiesta;
	public Object[] payload;
	
	private static final long serialVersionUID = 1159972224332743381L;

	public static enum TipoRichiesta {
		LOGIN,
		REGISTRAZIONE,
		VISUALIZZA_PROFILO,
		MODIFICA_PROFILO,
		VISUALIZZA_IMMAGINE_PROFILO,
		VISUALIZZA_ASTE,
		VISUALIZZA_ASTE_CONCLUSE,
		VISUALIZZA_ASTE_CORRENTI,
		VISUALIZZA_ASTE_PROGRAMMATE,
		VISUALIZZA_ASTE_VINTE,
		VISUALIZZA_ASTE_SALVATE,
		VISUALIZZA_ASTA,
		SALVA_ASTA,
		MODIFICA_ASTA,
		ANNULLA_ASTA,
		CREA_ASTA,
		VISUALIZZA_ARTICOLI,
		VISUALIZZA_ARTICOLO,
		CREA_ARTICOLO,
		MODIFICA_ARTICOLO,
		ELIMINA_ARTICOLO,
		VISUALIZZA_LOTTI,
		VISUALIZZA_LOTTO,
		CREA_LOTTO,
		MODIFICA_LOTTO,
		ELIMINA_LOTTO,
		CREA_CATEGORIA,
		VISUALIZZA_CATEGORIE,
		VISUALIZZA_PUNTATE,
		EFFETTUA_PUNTATA,
		VERIFICA_ADMIN,
		LOGOUT
	}
}
